version: "3.9"

services:
  web:
    build: .
    command: gunicorn chainpesa.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A chainpesa worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
